name: Build

on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:

permissions:
  contents: read

jobs:
  build-artifacts:
    name: Build Artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v5

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: Build solution
        run: dotnet build
              