name: Test

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed
    branches:
      - main

jobs:
  check-build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      build-succeeded: ${{ steps.check.outputs.result }}
    steps:
      - name: Check build status
        id: check
        run: echo "result=success" >> $GITHUB_OUTPUT

  unit-tests:
    needs: check-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            '9.0.x'
      - run: dotnet restore
      - name: Run unit tests
        run: dotnet test --no-restore --logger trx --collect:"XPlat Code Coverage"

      - name: Upload test results
        uses: actions/upload-artifact@v4.6.2
        with:
          name: unit-test-results
          path: TestResults/

  security-scan:
    needs: check-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run security scan
        run: |
          dotnet list package --vulnerable --include-transitive

  code-quality:
    needs: check-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            '9.0.x'

      - name: Run code analysis
        run: dotnet build --configuration Release --verbosity normal /p:TreatWarningsAsErrors=true
